### PR TITLE
Implement has_userphrase with chewing_userphrase_lookup

### PR DESCRIPTION
**Pull request by ShengYenPeng**
issue #96

### CODE REVIEW

**Comment by ShengYenPeng** [comment]
Hi @jserv , can you give me some suggestion for this pull request?

**Comment by jserv** [comment]
You have to explain the rationale with the commits and the exact reason why you implement something by deleting the code.

**Comment by ShengYenPeng** [comment]
The libchewing use `internal_has_userphrase` to implement `has_userphrase` by
 ` #define has_userphrase()  internal_has_userphrase()`.

According to czchen's description in issue 96, 
> After chewing_userphrase_lookup is implemented, has_userphrase shall use chewing_userphrase_lookup instead of libchewing internal functions.

I redefine `has_userphrase` by 
`#define has_userphrase()  chewing_userphrase_lookup()`

I think `internal_has_userphrase` is a temporary function waiting for `chewing_userphrase_lookup`,
now that `chewing_userphrase_lookup` has been implemented, we don't need `internal_has_userphrase` anymore.

**Comment by jserv** [comment]
Update GIT commit messages accordingly.

**Comment by jserv** [comment]
@ShengYenPeng : Thanks for your contribution.

**Comment by ShengYenPeng** [comment]
thanks for your suggestion!

**Pull request merged**
