### PR TITLE
add phrase

### PR DESCRIPTION
**Pull request by PeterDaveHello**
add 瑜伽墊 ㄩˊ ㄐㄧㄚ ㄉㄧㄢˋ

### CODE REVIEW

**Comment by jserv** [comment]
I am thinking of rejecting all pull requests which only add new phrases since they usually violates the sorted sequence in file `tsi.src`. Instead, we can create a new issue to allow efficient collaboration.

**Comment by kcwu** [comment]
@PeterDaveHello suggested maybe we can verify the sorting order in travis rule

**Comment by PeterDaveHello** [comment]
@kcwu yes, and also I can write an example of git-hooks to help contributor sort it before every commit.

**Comment by PeterDaveHello** [comment]
cc #214

**Pull request closed without merging**
