### PR TITLE
add lots of phrases

### PR DESCRIPTION
**Pull request by robert501128**
Add lots of phrases regarding [Issue#184](https://github.com/chewing/libchewing/issues/184)

Regarding the problem @jserv mentioned in [Issue#204](https://github.com/chewing/libchewing/pull/204)
I've created a [function](https://github.com/robert501128/addPhrases) for more easily adding phrases without breaking sorted sequence.

### CODE REVIEW

**Comment by hiunnhue** [comment]
``+胡至強``  這個是不是打錯字？胡志強？

**Comment by jserv** [comment]
You should place the scripts in directory `scripts`. For example, `scripts/lcov.sh`.

**Comment by PeterDaveHello** [comment]
Maybe we should figure out the good method to add phrases first.
https://github.com/chewing/libchewing/pull/197#issuecomment-203315368

**Comment by robert501128** [comment]
@jserv  Do you mean my addPhrase.py or my addPhrase.txt?

**Comment by robert501128** [comment]
I've corrected 胡志強, thanks

**Comment by jserv** [comment]
> Do you mean my addPhrase.py or my addPhrase.txt?

Yes, please use lowercase for consistent naming.

**Comment by robert501128** [comment]
Ok, I've added these.

**Comment by jserv** [comment]
I am considering closing this pull request due to the necessity of implementing uniform rules for adding new phrases and adjusting their frequency values. Without these rules, there is a risk of disrupting the current phrasing behavior.

**Pull request closed without merging**
