### PR TITLE
sort data/tsi.src

### PR DESCRIPTION
**Pull request by PeterDaveHello**
Sort `data/tsi.src` via `LANG=C sort` as we discussed in https://github.com/chewing/libchewing/pull/210#issuecomment-202697293 and https://github.com/chewing/libchewing/pull/210#issuecomment-202702887

### CODE REVIEW

**Comment by kcwu** [comment]
Thanks.

However the sorting order seems changed. On my machine (FreeBSD).
```
$ LANG=C sort tsi.src | hexdump -C | head -1
00000000  cb 87 20 31 20 cb 87 0a  cb 8a 20 31 20 cb 8a 0a  |.. 1 ..... 1 ...|
```
but yours are
```
$ hexdump -C tsi.src | head -1
00000000  e3 84 85 20 30 20 e3 84  85 0a e3 84 9b 20 30 20  |... 0 ....... 0 |
```
"cb" is less than "e3".

**Comment by kcwu** [comment]
Do you have time to check? I have to leave a while.

**Comment by PeterDaveHello** [comment]
So do I need to FreeBSD to sort?

**Comment by kcwu** [comment]
I tried on a linux machine,
```
$ env LANG=C sort tsi.src | hexdump -C | head -1
00000000  cb 87 20 31 20 cb 87 0a  cb 8a 20 31 20 cb 8a 0a  |.. 1 ..... 1 ...|
```

@PeterDaveHello Could you paste the output of `env LANG=C locale` ? There seems something different in your environment.

**Comment by PeterDaveHello** [comment]
Sure,

```
LANG=C
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```

**Comment by kcwu** [comment]
Looks like you explicitly set some locale variables. At least LC_COLLATE affects sorting order. Could you unset them before running sort?

**Comment by PeterDaveHello** [comment]
Fixed, thanks @kcwu 
```
$ LC_ALL=C LC_COLLATE=C LANG=C sort tsi.src | hexdump -C | head -1
00000000  cb 87 20 31 20 cb 87 0a  cb 8a 20 31 20 cb 8a 0a  |.. 1 ..... 1 ...|
```

**Comment by kcwu** [comment]
Thanks!

**Comment by PeterDaveHello** [comment]
Thanks @kcwu

**Pull request merged**
