### PR TITLE
Add ㄆㄧㄥˊ for 「评」、「岼」、「鲆」

### PR DESCRIPTION
**Pull request by PingNote**
平 Set = {平, 怦, 㛁, 評, 坪, 伻, 评, 抨, 砰, 秤, 萍, 呯, 岼, 泙, 玶, 枰, 胓, 蚲, 軯, 鲆, 鮃, 駍, 苹, 閛, 匉}

### CODE REVIEW

**Comment by PingNote** [comment]
Why https://travis-ci.org/chewing/libchewing/builds/77825565 **Succeeded** ,
but https://travis-ci.org/chewing/libchewing/builds/116166300 **Failed** ?

**Comment by PingNote** [comment]
Issue #199 : Travis CI failed

**Comment by PeterDaveHello** [comment]
Actually, 99eeb49 has nothing to do with this PR.

**Comment by jserv** [comment]
I can not find `评` via Ministry of Education, R.O.C. website: http://dict.revised.moe.edu.tw/cbdic/search.htm

**Comment by PeterDaveHello** [comment]
@PingNote I'll respectfully suggest you to drop 99eeb49 and rebase your branch with the latest master branch, #196 already did the CI fix in commit ded706312dc60 and been merged yesterday.

**Comment by PingNote** [comment]
Thanks @jserv , I had gone to check `平` series phrases .

`评` and `鲆` are simplified chinese phrases , `岼` may be is japanese phrase .

International Encoded Han Character and Variants Database http://chardb.iis.sinica.edu.tw/
`评` http://chardb.iis.sinica.edu.tw/variants.jsp?cid=22566
`鲆` http://chardb.iis.sinica.edu.tw/variants.jsp?cid=26896
`岼` http://chardb.iis.sinica.edu.tw/search.jsp?q=%E5%B2%BC

Wiktionary https://zh.wiktionary.org/zh-hant/
`平` series phrases https://zh.wiktionary.org/zh-hant/%E5%B9%B3
`评` https://zh.wiktionary.org/wiki/%E8%AF%84
`鲆` https://zh.wiktionary.org/wiki/%E9%B2%86
`岼` https://zh.wiktionary.org/zh-hant/%E5%B2%BC

Chinese Text Project  http://ctext.org/
`平` series phrases http://ctext.org/dictionary.pl?char=%E5%B9%B3%2B
`评` http://ctext.org/dictionary.pl?char=%E8%AF%84
`鲆` http://ctext.org/dictionary.pl?char=%E9%B2%86
`岼` (References - Kangxi: p.310#07 , Hanyu: v1,p0766#08) http://ctext.org/dictionary.pl?char=%E5%B2%BC

**Comment by PingNote** [comment]
Thanks @PeterDaveHello , I dropped https://github.com/chewing/libchewing/commit/99eeb49afb08a25b54099a0cba94fa2897f1a01f , and I pushed again :)

**Comment by czchen** [comment]
@PingNote 

Not sure if I understand correctly, these three words are not from traditional Chinese, right?

**Comment by jserv** [comment]
libchewing would only accept Traditional Chinese characters.

**Pull request closed without merging**
