### PR TITLE
Minor cleanups

### PR DESCRIPTION
**Pull request by Chocobo1**
I've scanned the project with [cppcheck](http://cppcheck.sourceforge.net/) and done some cleanups. Please take a look.

### CODE REVIEW

**Comment by czchen** [comment]
@Chocobo1 Thank for the contribution. However, please help to rebase your code since I cannot merge your code due to conflict, thanks.

**Comment by Chocobo1** [comment]
Should be fine by now

**Comment by Chocobo1** [comment]
BTW, ever consider using [Coverity Scan](https://scan.coverity.com/)? It can integrate with Travis Ci and much more powerful than cppcheck.

**Comment by czchen** [comment]
I will try to setup the Coverity Scan, thanks for suggestion.

**Comment by czchen** [comment]
@Chocobo1 Coverity Scan is ready now.

**Pull request merged**
