### PR TITLE
Covertiy Scan fixes

### PR DESCRIPTION
**Pull request by Chocobo1**
Please review carefully, thanks.

### CODE REVIEW

**Comment by kcwu** [comment]
how about use strlcpy instead of strncpy?

**Comment by Chocobo1** [comment]
AFAIK strlcpy is only available on BSD-like systems, I don't know if it's really ok to add strlcpy to code base which also adds some complexity...

**Comment by kcwu** [comment]
Ah, you are right.

**Comment by czchen** [comment]
@Chocobo1 @kcwu 

I think it is error prone to use `strncpy` since we need to minus one in size parameter to ensure the string is null terminated. For example:
```
strncpy(buf->char_, chibuf, sizeof(buf->char_) - 1);
```
Since `strlcpy` has portability problem, maybe we shall change to use `snprintf` to replace `strncpy`. `snprintf` guarantees null-terminated and buffer size check. It just looks strange in the place everyone expects `strcpy` or similar. Any suggestion on using `snprintf` to replace `strncpy`?

**Comment by Chocobo1** [comment]
Yes, by using snprintf we could ensure string will always be terminated, but we still need to concentrate on its length: characters after (n-1) is not going to be copied.

code will look like this:
`char a[n];  //human check if n > sizeof(from)`
`snprintf(a, sizeof(a), "%s" , from);`

After googling this, I don't think there will be a clean/perfect solution to this problem in pure C world, so I really don't have any opinion on this: you ok, I ok.

ps. in my commits, I was just thinking the most effective/unintrusive way to fix it.

**Pull request merged**
