### PR TITLE
Import 89525 phrases from the MOE revised dict.

### PR DESCRIPTION
**Pull request by PeterDaveHello**
Dropped single word as discussed with @jserv,
so that we don't need to care about the order here.

The dictionary maintained my Ministry of Education, R.O.C:
 - http://dict.revised.moe.edu.tw/cbdic/

License reference:
 - http://resources.publicense.moe.edu.tw/
 - http://dict.revised.moe.edu.tw/cgi-bin/cbdic/gsweb.cgi?ccd=SBTjWJ&o=e0&sec=sec11&option=linkout004&actice=layout

I use the g0v/moedict-data as the source to import the phrases,
since it's in json format, it's easier to work with it.

g0v/moedict-data:
 - https://github.com/g0v/moedict-data

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
PS: This PR covered the phrase in #201

**Comment by PeterDaveHello** [comment]
cc @lucienchlin

**Comment by kcwu** [comment]
please sort the file. otherwise we cannot see the diff.

**Comment by PeterDaveHello** [comment]
@kcwu is there any tool can help sorting this? I opened #205 about that problem but no response, and @jserv told me there is no need to sort that, hope I didn't misunderstand it.

**Comment by kcwu** [comment]
In the past, we just use sort(1) with "C" locale to sort it.

I still prefer sorting because it will be easier to know something duplicated or inconsistency via git diff.

**Comment by PeterDaveHello** [comment]
If that's required, there should be a tool to help sorting, wothout that, even though git diff can help, you still can not make sure there is no duplicated words.

**Comment by jserv** [comment]
@PeterDaveHello : you can figure out the sort usage by checking the `git log`. File `tsi.src` should be sorted in order to get compared and revised while `phone.cin` is a different case.

**Comment by PeterDaveHello** [comment]
Okay, I'll check that, thanks.

**Comment by kcwu** [comment]
To be clear, you can just sort it using simple command line like
```
$ env LANG=C sort tsi.src > tmp && mv tmp tsi.src
```
Since it is easy to do with various third party utilities, we didn't provide a specific tool.

----
Back to the original topic, import phrases from MOEDICT. Basically, I like the idea to import subset of MOEDICT. However, I am a bit nervous to import ALL of them since some of them are out dated. As MOEDICT claimed it includes many ancient phrases for research purpose, I am not sure whether it is good for libchewing, whose main purpose is input method.

**Comment by PeterDaveHello** [comment]
@kcwu:

Thanks, I have a question here, maybe also a problem, if I didn't do it wrong, by using `env LANG=C sort tsi.src` in the master branch, seems the current `tsi.src` is in a wrong order, I'm not sure if you or other maintainers will want me to sort it first, or just sort with the new imported phrases? Don't we need to make sure the order in master branch is the same as `sort` sorted? I can send a PR to add it to `.travis.yml` so that CI can make sure that. Thanks for your reply.

**Comment by czchen** [comment]
@PeterDaveHello 

* Please sort the `tsi.src` in master branch and send a PR for it, and the import the data from MOEDICT after `tsi.src` is sorted.

* We really need to review the data from MOEDICT. At least I think any phrases bigger than 6 words are not useful at all.

**Comment by PeterDaveHello** [comment]
Sorted in #212, thanks @czchen

**Comment by PeterDaveHello** [comment]
I'll update this PR once #212 been merged.

**Comment by PeterDaveHello** [comment]
PR updated.

**Comment by czchen** [comment]
@PeterDaveHello 

Please help to check CI fails.

**Comment by PeterDaveHello** [comment]
@czchen I've asked for advice from @jserv and @lucienchlin via emails, and I am going to close this PR since there is license issue, I'll find another way to improve chewing's dict soon.

**Pull request closed without merging**
